import { Document, Page, StyleSheet, Text, View, Link } from "@react-pdf/renderer";
import type { ContinuityIntake, ContinuityPlan } from "@/types";

const styles = StyleSheet.create({
  page: { padding: 56, fontFamily: "Helvetica", fontSize: 11, color: "#1D1D1F" },
  h1: { fontSize: 22, fontWeight: 600, marginBottom: 4 },
  h2: { fontSize: 14, fontWeight: 600, marginTop: 18, marginBottom: 6 },
  meta: { fontSize: 9, color: "#6E6E73" },
  para: { lineHeight: 1.5, marginBottom: 6 },
  itemTitle: { fontWeight: 600, marginTop: 6 },
  pill: {
    fontSize: 9,
    padding: 3,
    color: "#1D1D1F",
    backgroundColor: "#FAFAFA",
    borderRadius: 4,
  },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 56,
    right: 56,
    fontSize: 9,
    color: "#6E6E73",
    borderTop: "1pt solid #EAEAEA",
    paddingTop: 8,
  },
});

export function ContinuityPDF({
  plan,
  intake,
}: {
  plan: ContinuityPlan;
  intake: ContinuityIntake;
}) {
  const today = new Date().toISOString().slice(0, 10);
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.h1}>Continuity of care plan</Text>
        <Text style={styles.meta}>
          Generated by Seagull on {today} · From {intake.current_state} to{" "}
          {intake.destination_state || "exploring"} · Timeline: {intake.timeline}
        </Text>

        <Section title="1. Records transfer">
          <Checklist items={plan.records_transfer.items} />
          <Text style={styles.itemTitle}>Template letter</Text>
          <Text style={styles.para}>{plan.records_transfer.template_letter}</Text>
        </Section>

        <Section title="2. Insurance continuity">
          <Checklist items={plan.insurance_continuity.items} />
          <Text style={styles.para}>{plan.insurance_continuity.state_notes}</Text>
        </Section>

        <Section title="3. Medication gap risk">
          <Text style={styles.pill}>Risk: {plan.medication_gap_risk.level.toUpperCase()}</Text>
          <Text style={styles.para}>{plan.medication_gap_risk.rationale}</Text>
          <Checklist items={plan.medication_gap_risk.items} />
        </Section>

        <Section title="4. Finding new care">
          <Text style={styles.itemTitle}>Questions to ask</Text>
          {plan.finding_new_care.questions_to_ask.map((q, i) => (
            <Text key={i} style={styles.para}>
              • {q}
            </Text>
          ))}
          <Text style={styles.itemTitle}>Red flags</Text>
          {plan.finding_new_care.red_flags.map((r, i) => (
            <Text key={i} style={styles.para}>
              • {r}
            </Text>
          ))}
          <Checklist items={plan.finding_new_care.items} />
        </Section>

        <Section title="5. Legal and ID">
          <Checklist items={plan.legal_and_id.items} />
        </Section>

        <Section title="6. Community resources">
          {plan.community_resources.items.map((r, i) => (
            <View key={i} style={{ marginBottom: 6 }}>
              <Text style={styles.itemTitle}>{r.name}</Text>
              {r.note && <Text style={styles.para}>{r.note}</Text>}
              <Link src={r.url}>{r.url}</Link>
            </View>
          ))}
        </Section>

        <Text style={styles.footer}>
          Generated by Seagull on {today}. This is organizational support, not legal or
          medical advice.
        </Text>
      </Page>
    </Document>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View wrap={false}>
      <Text style={styles.h2}>{title}</Text>
      {children}
    </View>
  );
}

function Checklist({ items }: { items: Array<{ title: string; detail: string }> }) {
  return (
    <View>
      {items.map((item, i) => (
        <View key={i} style={{ marginBottom: 6 }}>
          <Text style={styles.itemTitle}>☐ {item.title}</Text>
          <Text style={styles.para}>{item.detail}</Text>
        </View>
      ))}
    </View>
  );
}
