import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  Link,
} from "@react-pdf/renderer";
import type { IncidentPacket, ProtectionRecord } from "@/types";

const styles = StyleSheet.create({
  page: { padding: 56, fontFamily: "Helvetica", fontSize: 11, color: "#1D1D1F" },
  h1: { fontSize: 22, fontWeight: 600, marginBottom: 4 },
  h2: { fontSize: 14, fontWeight: 600, marginTop: 18, marginBottom: 6 },
  meta: { fontSize: 9, color: "#6E6E73" },
  para: { lineHeight: 1.5, marginBottom: 6 },
  tableRow: { flexDirection: "row", borderBottom: "1pt solid #EAEAEA", paddingVertical: 4 },
  tableHead: { flexDirection: "row", borderBottom: "1pt solid #1D1D1F", paddingVertical: 4 },
  cell: { flex: 1, paddingRight: 6 },
  cellHead: { flex: 1, paddingRight: 6, fontWeight: 600, fontSize: 10 },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 56,
    right: 56,
    fontSize: 9,
    color: "#6E6E73",
    borderTop: "1pt solid #EAEAEA",
    paddingTop: 8,
  },
  pill: {
    fontSize: 8,
    color: "#6E6E73",
    borderRadius: 6,
    padding: 2,
  },
});

const INCIDENT_LABELS: Record<string, string> = {
  housing: "Housing",
  employment: "Employment",
  healthcare: "Healthcare",
  public_accommodation: "Public accommodation",
  other: "Other",
};

const NEXT_STEPS: Record<string, Array<{ name: string; url: string; note: string }>> = {
  employment: [
    {
      name: "EEOC",
      url: "https://www.eeoc.gov/filing-charge-discrimination",
      note: "File a charge of discrimination within 180 days (300 days in some states).",
    },
  ],
  housing: [
    {
      name: "HUD Fair Housing",
      url: "https://www.hud.gov/program_offices/fair_housing_equal_opp/online-complaint",
      note: "File a fair housing complaint within one year of the incident.",
    },
  ],
  healthcare: [
    {
      name: "HHS Office for Civil Rights",
      url: "https://www.hhs.gov/civil-rights/filing-a-complaint/index.html",
      note: "File a Section 1557 complaint within 180 days.",
    },
  ],
  public_accommodation: [
    {
      name: "DOJ Civil Rights Division",
      url: "https://civilrights.justice.gov/",
      note: "Report a public accommodation incident.",
    },
  ],
  other: [
    {
      name: "Lambda Legal Help Desk",
      url: "https://www.lambdalegal.org/help",
      note: "Free intake to determine the right filing venue.",
    },
  ],
};

export function IncidentPDF({ packet }: { packet: IncidentPacket }) {
  const today = new Date().toISOString().slice(0, 10);
  const nextSteps = NEXT_STEPS[packet.incident_type || "other"];

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.h1}>Incident documentation packet</Text>
        <Text style={styles.meta}>
          Generated by Seagull on {today} ·{" "}
          {packet.incident_type ? INCIDENT_LABELS[packet.incident_type] : "Uncategorized"}
        </Text>

        <Text style={styles.h2}>Summary</Text>
        <Text style={styles.para}>
          {packet.summary || "Not yet generated."}
        </Text>

        <Text style={styles.h2}>Timeline of events</Text>
        <Text style={styles.para}>
          {packet.incident_date
            ? `${packet.incident_date}${
                packet.incident_location_city || packet.incident_location_state
                  ? " — " +
                    [packet.incident_location_city, packet.incident_location_state]
                      .filter(Boolean)
                      .join(", ")
                  : ""
              }`
            : "Date not captured."}
          {"\n\n"}
          {packet.what_happened || "No narrative captured."}
        </Text>

        <Text style={styles.h2}>Parties involved</Text>
        <Table
          headers={["Name", "Role"]}
          rows={(packet.parties_involved || []).map((p) => [p.name, p.role])}
        />

        <Text style={styles.h2}>Witnesses</Text>
        <Table
          headers={["Name", "Contact", "What they saw"]}
          rows={(packet.witnesses || []).map((w) => [
            w.name,
            w.contact || "—",
            w.what_they_saw,
          ])}
        />

        <Text style={styles.h2}>Evidence inventory</Text>
        <Table
          headers={["Type", "Description", "Location"]}
          rows={(packet.evidence || []).map((e) => [e.type, e.description, e.location])}
        />

        <Text style={styles.h2}>Applicable legal protections</Text>
        {(packet.applicable_protections || []).length === 0 ? (
          <Text style={styles.para}>None looked up yet.</Text>
        ) : (
          (packet.applicable_protections as ProtectionRecord[]).map((p, i) => (
            <View key={i} style={{ marginBottom: 6 }}>
              <Text style={{ fontWeight: 600 }}>{p.title}</Text>
              <Text style={styles.meta}>{p.citation}</Text>
              <Text style={styles.para}>{p.summary}</Text>
              {p.url && <Link src={p.url}>{p.url}</Link>}
            </View>
          ))
        )}

        <Text style={styles.h2}>Suggested next steps</Text>
        {nextSteps.map((step, i) => (
          <View key={i} style={{ marginBottom: 6 }}>
            <Text style={{ fontWeight: 600 }}>{step.name}</Text>
            <Text style={styles.para}>{step.note}</Text>
            <Link src={step.url}>{step.url}</Link>
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by Seagull on {today}. This is documentation, not legal advice.
        </Text>
      </Page>
    </Document>
  );
}

function Table({ headers, rows }: { headers: string[]; rows: string[][] }) {
  if (rows.length === 0) {
    return <Text style={styles.para}>Not yet captured.</Text>;
  }
  return (
    <View>
      <View style={styles.tableHead}>
        {headers.map((h) => (
          <Text key={h} style={styles.cellHead}>
            {h}
          </Text>
        ))}
      </View>
      {rows.map((row, ri) => (
        <View style={styles.tableRow} key={ri}>
          {row.map((cell, ci) => (
            <Text key={ci} style={styles.cell}>
              {cell || "—"}
            </Text>
          ))}
        </View>
      ))}
    </View>
  );
}
