import { PKPass } from "passkit-generator";
import type { Profile } from "@/lib/profile";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface PassRequest {
  profile?: Profile;
  reason?: string;
  goals?: string[];
}

/**
 * Generates a signed .pkpass file that iOS Safari will offer to add to
 * Apple Wallet. Apple requires the pass to be signed with a Pass Type ID
 * certificate; without one the route returns a 503 with instructions.
 *
 * Required environment variables to enable signing:
 *   APPLE_PASS_TYPE_ID   e.g. "pass.com.seagull.previsit"
 *   APPLE_TEAM_ID        Apple Developer team ID
 *   APPLE_PASS_CERT      PEM-encoded Pass Type ID cert
 *   APPLE_PASS_KEY       PEM-encoded private key for that cert
 *   APPLE_PASS_KEY_PASS  passphrase for the key (optional)
 *   APPLE_WWDR_CERT      PEM-encoded Apple WWDR intermediate cert
 *   APPLE_PASS_ICON_PNG  base64-encoded 29x29 icon.png (optional override)
 */
export async function POST(req: Request) {
  let body: PassRequest;
  try {
    body = await req.json();
  } catch {
    return json({ error: "invalid json" }, 400);
  }

  const profile = body.profile;
  const reason = (body.reason || "").trim();
  if (!profile || !reason) {
    return json({ error: "profile and reason are required" }, 400);
  }

  const passTypeId = process.env.APPLE_PASS_TYPE_ID;
  const teamId = process.env.APPLE_TEAM_ID;
  const signerCert = process.env.APPLE_PASS_CERT;
  const signerKey = process.env.APPLE_PASS_KEY;
  const wwdr = process.env.APPLE_WWDR_CERT;

  if (!passTypeId || !teamId || !signerCert || !signerKey || !wwdr) {
    return json(
      {
        error:
          "Apple Wallet signing not configured on this deployment. Save the image instead, or ask the operator to add the Apple Pass Type ID certificate.",
      },
      503
    );
  }

  const allergies = profile.allergies
    .filter((a) => a.substance.trim())
    .map((a) => (a.reaction ? `${a.substance} (${a.reaction})` : a.substance))
    .join(", ");
  const goals = (body.goals || []).map((g) => (g || "").trim()).filter(Boolean);

  const demoBits = [
    profile.age && `${profile.age}y`,
    profile.sex_assigned_at_birth && `${profile.sex_assigned_at_birth} at birth`,
  ]
    .filter(Boolean)
    .join(" · ");

  const passJson = {
    formatVersion: 1,
    passTypeIdentifier: passTypeId,
    teamIdentifier: teamId,
    organizationName: "Seagull",
    serialNumber: `seagull-${Date.now()}`,
    description: "Previsit Card",
    backgroundColor: "rgb(15, 42, 63)",
    foregroundColor: "rgb(255, 255, 255)",
    labelColor: "rgb(186, 230, 253)",
    logoText: "Previsit Card",
    generic: {
      primaryFields: [
        {
          key: "name",
          label: profile.pronouns ? `Patient (${profile.pronouns})` : "Patient",
          value: profile.display_name.trim() || "Patient",
        },
      ],
      secondaryFields: [
        ...(demoBits
          ? [{ key: "demo", label: "DEMOGRAPHICS", value: demoBits }]
          : []),
        {
          key: "allergies",
          label: "ALLERGIES",
          value: allergies || "No known allergies",
          textAlignment: "PKTextAlignmentRight",
        },
      ],
      auxiliaryFields: [
        {
          key: "reason",
          label: "TODAY",
          value: reason,
        },
      ],
      backFields: [
        ...(goals.length
          ? [
              {
                key: "goals",
                label: "Ranked goals for today",
                value: goals.map((g, i) => `${i + 1}. ${g}`).join("\n"),
              },
            ]
          : []),
        ...(profile.anatomical_inventory
          ? [
              {
                key: "anatomy",
                label: "Anatomy",
                value: profile.anatomical_inventory,
              },
            ]
          : []),
        ...(profile.hormone_regimen_summary
          ? [
              {
                key: "regimen",
                label: "Hormone context",
                value: profile.hormone_regimen_summary,
              },
            ]
          : []),
        {
          key: "disclaimer",
          label: "About this pass",
          value:
            "Patient self-report, not a medical record. Generated by Seagull.",
        },
      ],
    },
  };

  try {
    const pass = new PKPass(
      {
        "pass.json": Buffer.from(JSON.stringify(passJson)),
      },
      {
        wwdr,
        signerCert,
        signerKey,
        signerKeyPassphrase: process.env.APPLE_PASS_KEY_PASS,
      }
    );

    const buffer = pass.getAsBuffer();
    const body = new Uint8Array(buffer);

    return new Response(body, {
      status: 200,
      headers: {
        "content-type": "application/vnd.apple.pkpass",
        "content-disposition": 'attachment; filename="previsit.pkpass"',
        "cache-control": "no-store",
      },
    });
  } catch (e: any) {
    return json(
      { error: `Pass signing failed: ${e?.message || "unknown"}` },
      500
    );
  }
}

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}
